protos/gk/v1/gatekeeper.proto
src/datastore/collections.cpp
src/datastore/collections.h
src/datastore/collections_test.cpp
src/datastore/identities.cpp
src/datastore/identities.h
src/datastore/identities_test.cpp
src/err/errors.h
src/service/grpc.cpp
src/service/grpc_test.cpp
src/service/mappers.cpp

Update _Collections_ and _Identities_ endpoints to allow setting IDs during creation instead of only allowing autogenerated IDs.

Update gRPC endpoints for Collections and Identities

---

.github/workflows/build.yaml
.github/workflows/ci.yaml
CMakeLists.txt
cmake/dependencies.cmake
cmake/googleapis.cmake
proto/CMakeLists.txt
src/CMakeLists.txt

Building gRPC from source (via FetchContent) extends the overall build time significantly. This change allow using system installed gRPC if available to reduce the build time.

Optimise build time

---

.github/workflows/ci.yaml
CMakeLists.txt
Makefile
src/datastore/CMakeLists.txt
src/err/CMakeLists.txt
src/service/CMakeLists.txt

Use clang's source-based code coverage (`llvm-cov`) instead of `gcov`.

Source based code coverage

---

.github/workflows/build.yaml
cmake/dependencies.cmake

Due to _Homebrew Bottle_ for gRPC not including test headers we have to compile gRPC from source, which adds a significant amount of time to the total compile time. This change reduces the macOS build time by using system libs for gRPC dependencies.

Optimise macOS build workflow

---

src/service/grpc.cpp
src/service/grpc.h
src/service/grpc_test.cpp

gRPC endpoints to add, list and remove collection members.
⚠️ This PR is missing error handling and pagination for listing members which are expected to be implemented separately.

Collection Members endpoints

---

datastore/schema.sql

This issue changes the names of junction tables by swapping the referred tables and prefixing the names with the policy tables (e.g. `identities_rbac-policies` becomes `rbac-policies_identities`)

Change names of junction tables

---

datastore/schema.sql
proto/gk/v1/gatekeeper.proto
src/datastore/CMakeLists.txt
src/datastore/access-policies.cpp
src/datastore/access-policies.h
src/datastore/access-policies_test.cpp
src/datastore/collections.cpp
src/datastore/collections.h
src/datastore/collections_test.cpp
src/datastore/identities.cpp
src/datastore/identities.h
src/datastore/identities_test.cpp
src/datastore/policies.h
src/datastore/rbac-policies.cpp
src/datastore/rbac-policies.h
src/datastore/roles.h
src/service/grpc.cpp
src/service/grpc.h
src/service/grpc_test.cpp
src/service/mappers.cpp
src/service/mappers.h

Implement gRPC endpoint to consume rebuild cache events and re-create or update redis entries for _Access_ and _RBAC_ policies.

Rebuild cache

---

proto/gk/v1/gatekeeper.proto
src/datastore/rbac-policies.cpp
src/datastore/rbac-policies.h
src/service/grpc.cpp
src/service/grpc_test.cpp
src/service/mappers.cpp

Using principals instead of collections and identities adds more complexity to the gRPC endpoints and doesn't give a significant advantage.

Drop principals type

---

proto/gk/v1/gatekeeper.proto
src/datastore/identities.cpp
src/datastore/identities.h
src/datastore/identities_test.cpp
src/service/grpc.cpp
src/service/grpc.h
src/service/grpc_test.cpp
src/service/mappers.cpp
src/service/mappers.h

`LookupIdentities` gRPC endpoint is a bit odd since it attempts to retrieve an identity by `sub` and the response (`LookupIdentitiesResponse`) returns a list of identities which will have either `0` entries (if there are no matches) or `1` entry if there is a match. Since `sub` must be unique across identities there can't be more than 1 result. 
This change is to drop the `LookupIdentities` gRPC endpoint and update `RetrieveIdentity` endpoint to allow retrieving identities by `sub`.

Drop lookup identities

---

src/datastore/CMakeLists.txt
src/datastore/config.h
src/datastore/pg.cpp
src/datastore/pg.h
src/datastore/pg_test.cpp
src/datastore/redis.h
src/err/basic_error.h
src/err/errors.h
src/err/fixed_string.h
src/logger/logger.h

Update pg connections to be thread-safe and potentially fault tolerant by attempting to reconnect when connections are broken.

Thread-safe Postgres connections

---

proto/gk/v1/access.proto
src/datastore/access-policies.cpp
src/datastore/access-policies.h
src/events/concepts.h
src/svc/access.cpp
src/svc/access.h
src/svc/access_test.cpp

- (proto) add `DeletePolicyIdentity` endpoint
- (datastore) `AccessPolicy.deleteIdentity`
- (svc) `Access.DeletePolicyIdentity`

Add `DeletePolicyIdentity` endpoint to `Access`

---

src/svc/access.cpp
src/svc/rbac.cpp

It seems when the redis connection is in a bad state the server can't recover. As a temporary measure, log potentially unhandled exceptions related to redis and exit.

Log and exit for unhandled exceptions potentially related to redis

---

README.md
db/schema.sql
src/db/principals.cpp
src/db/principals.h
src/db/principals_test.cpp
src/db/records.cpp
src/db/records.h
src/db/records_test.cpp
src/svc/CMakeLists.txt
src/svc/authz.cpp
src/svc/authz.h
src/svc/authz_test.cpp
src/svc/common.h
src/svc/principals.cpp
src/svc/principals.h
src/svc/principals_test.cpp
src/svc/resources.cpp
src/svc/resources_test.cpp

Use `space-id` gRPC metadata (i.e. HTTP/2 header) to create data silos to support multi-tenancy.

Multi-tenancy

---

db/schema.sql
src/db/tuples.cpp
src/db/tuples.h
src/db/tuples_test.cpp
src/svc/authz.cpp
src/svc/authz.h
src/svc/authz_test.cpp

ReBAC implementation is based on relation tuples which can be used for storing authorisation records.
This change is to update all Authz gRPC service endpoints to use `tuples` instead of `records`. Records will be dropped after moving all functionality to Tuples.

Change Authz service to use tuples instead of records

---

proto/sentium/api/v1/relations.proto
src/db/tuples.cpp
src/db/tuples.h
src/db/tuples_test.cpp
src/err/errors.h
src/svc/common.h
src/svc/principals.cpp
src/svc/relations.cpp
src/svc/relations.h
src/svc/relations_test.cpp

Add list left method to the Relations gRPC service.

List Relations (left)

---

src/svc/resources.cpp
src/svc/resources.h
src/svc/resources_test.cpp

Since authorisation records are now stored in `tuples` (#77), we need to update Resources gRPC endpoints to use `tuples` instead of `records`.

Change Resources service to use tuples instead of records

---

README.md
proto/sentium/api/v1/authz.proto
src/svc/authz.cpp
src/svc/authz_test.cpp

Favour _entity_ over _resource_ for protobuf field names. 
💡 Since this is just a field name change (and not type or number change) this is a non-breaking change.

Tidy-up Authz gRPC service

---

Makefile
bench/CMakeLists.txt
bench/algorithms_test.cpp
bench/relations_test.cpp
proto/sentium/api/v1/relations.proto
src/db/tuples.h
src/err/errors.h
src/svc/relations.cpp
src/svc/relations.h
src/svc/relations_test.cpp

Introduce `set` strategy for checking relations, which uses a set intersection algorithm to derive relations between entities if a direct relation cannot be found.
💡 Refer to tests for a visual example on how the `set` strategy works.

ReBAC: `set` strategy for checking relations

---

Makefile
bench/relations_test.cpp
proto/sentium/api/v1/relations.proto
src/svc/relations.cpp
src/svc/relations.h
src/svc/relations_test.cpp

Introduce `graph` strategy for checking relations between two entities. The implementation uses a BFS graph traversal to derive relations if no direct relation is found.

ReBAC: `graph` strategy for checking relations

---

docs/rebac.md
src/svc/relations.cpp
src/svc/relations.h
src/svc/relations_test.cpp

This is a slight optimisation to reduce the BFS graph traversal cost with the expectation that the graph is narrower on the left and wider on the right. Most of the time this would be the case if principals are on the left. 
e.g. 
In the following example, to check `user:jane -> reader -> doc:notes.txt` with left to right BFS will require 10003 lookups whereas right to left will only take 3 lookups.
<details>
<summary>Before</summary>
```
-------------------------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------
bm_relations/check_graph/4/128     25076263 ns      3086440 ns          100 …
```

Traverse relations graph right to left when checking relations

---

bench/algorithms_test.cpp
db/schema.sql
src/db/CMakeLists.txt
src/db/tuples.cpp
src/db/tuples.h
src/db/tuples_test.cpp
src/db/tuplets.cpp
src/db/tuplets.h
src/db/tuplets_test.cpp
src/err/errors.h
src/svc/relations.cpp
src/svc/relations_test.cpp

Comparing `int64`s (8 bytes fixed length) is more efficient than comparing variable length strings. This change attempts to utilises this efficiency to reduce latencies when checking relations (specially when using `set` strategy). 
A pre-computed `int64` hash values for tuples' left and right entities are stored in the DB along with an index specifically created to yield index only scans when retrieving data for the `set` strategy. This index is also used to achieve a favourable query plan when listing tuples for the `graph` strategy.
Additional computations, hash data and index writes results in slightly slower writes but better reads.
```
Load Average: 1.84, 2.01, 2.03
------------------------------------------------------------------------------------------
Benchmark …
```

Use hash values to speed-up to comparing entities

---

.github/workflows/publish.yaml
Containerfile
bin/march.sh
src/svc/authz.h
src/svc/entities.h
src/svc/principals.h
src/svc/relations.h

There seems to be an issue with `ghcr.io` where published containers can't be pulled ('manifest unknown' error), so moving to `docker.io`.
**Update:** https://github.com/docker/build-push-action/issues/820#issuecomment-1486849546 suggested the issue could be due to cross-compiling/how multi-arch images are created. After updating the builds to use g++ cross-compile (instead of using QEMU to create multi-arch containers) it seems `docker` can pull ghcr.io images now.
Inspecting the builds produced by https://github.com/uatuko/ruek/actions/runs/11767516276 seems to show both ghcr.io and docker.io having the same build manifests.
<details>
<summary>ghcr.io/uatuko/ruek</summary>
```
$ docker buildx imagetools inspect ghcr.io/uatuko/ruek
Name:      ghcr.io/uatuko/ruek:latest
MediaType: …
```

Publish containers to docker.io

---

src/svc/relations.cpp
src/svc/relations_test.cpp

Return `ALREADY_EXISTS` gRPC status when creating duplicate relations.

Fix to return correct gRPC errors when creating duplicate relations

---

CMakeLists.txt
Containerfile

Use `ubuntu:24.04` for container builds since gRPCxx v0.6.1 require cmake 3.27 (which isn't available in current stable `debian:12-slim`).

Fix publish workflow
